# Generated by Django 5.1.6 on 2025-02-07 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_reception', models.DateTimeField(blank=True, null=True)),
                ('data_dispatch', models.DateTimeField(blank=True, null=True)),
                ('dispatches', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('flightNumber', models.CharField(max_length=255, null=True)),
                ('capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.capital')),
                ('category_status', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.categorymailmodel')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.country')),
                ('sex_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otkuda', to='shipment.sexmodel')),
                ('sex_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuda', to='shipment.sexmodel')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.statusmodel')),
                ('tranzit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.transitmodel')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.typemodel')),
            ],
        ),
    ]
