# Generated by Django 5.1.6 on 2025-02-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
        ('shipment', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='dispatch',
            name='country',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='from_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuda_capital', to='shipment.capital'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='to_capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otkuda_capital', to='shipment.capital'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='to_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otkuda_country', to='shipment.country'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='note',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='sex_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='otkuda', to='shipment.sexmodel'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='sex_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='kuda', to='shipment.sexmodel'),
        ),
    ]
