# Generated by Django 5.1.6 on 2025-02-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_remove_dispatch_capital_remove_dispatch_country_and_more'),
        ('shipment', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='from_capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuda_capital', to='shipment.capital'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='from_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuda_country', to='shipment.country'),
        ),
    ]
