# Generated by Django 5.1.6 on 2025-02-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_dispatch_from_capital_alter_dispatch_from_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
