# Generated by Django 5.1.6 on 2025-02-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_alter_dispatch_note'),
        ('shipment', '0003_alter_capital_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='sex_1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otkuda', to='shipment.sexmodel'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='sex_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuda', to='shipment.sexmodel'),
        ),
    ]
