# Generated by Django 5.1.6 on 2025-02-17 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_alter_dispatch_sex_1_alter_dispatch_sex_2'),
        ('shipment', '0003_alter_capital_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.statusmodel'),
        ),
    ]
