# Generated by Django 5.1.6 on 2025-02-19 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0006_alter_dispatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
