# Generated by Django 5.1.6 on 2025-02-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_capital_country_alter_capital_id_alter_capital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.country'),
        ),
    ]
